### ISSUE TITLE
keyframes not being parsed in CSS files

### ISSUE THREAD

**Issue by dwachss** [scssphp/scssphp#125]
Importing "keyframes" as:
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(359deg);
  }
}

in a .css file gives the error:
Uncaught ScssPhp\ScssPhp\Exception\ParserException: SCSS syntax not allowed in CSS file

This is the correct *css* syntax; it should not be interpreted as scss.

**Comment by dwachss** [comment]
I get a similar error ('unexpected }') with selector::before.
 Both these work fine in scss files; you are just marking them in error in css files.

**Comment by dwachss** [comment]
I made some test files, at http://kavanot.name/css/styletest.php?testfile=1

The PHP is:
```php
<?php
require_once "scss.inc.php";

use ScssPhp\ScssPhp\Compiler;

$scss = new Compiler();
$scss->addImportPath(function($path) {
    if (!file_exists($path)) return null;
    return $path;
});

if ($_GET['testfile'] == 1){
	echo $scss->compile('@import "test1.css";');
}else if ($_GET['testfile'] == 2){
	echo $scss->compile('@import "test2.css";');
}else if ($_GET['testfile'] == 3){
	echo $scss->compile('@import "test3.css";');
}

?>
```

The test files are:

test1.css:
```css
div {
	color: blue;
}
```
and http://kavanot.name/css/styletest.php?testfile=1 gives

```css
div { color: blue; }
```

----

test2.css:

```css
div::before {
	content: ':)';
}
```

and http://kavanot.name/css/styletest.php?testfile=2 gives

```html
<br />
<b>Fatal error</b>:  Uncaught ScssPhp\ScssPhp\Exception\ParserException: unexpected }: failed at test2.css on line 4, at column 2 in/css/src/Parser.php:149
```

----

test3.css:

```css
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(359deg);
  }
}
```

and http://kavanot.name/css/styletest.php?testfile=3 gives

```html
<br />
<b>Fatal error</b>:  Uncaught ScssPhp\ScssPhp\Exception\ParserException: SCSS syntax not allowed in CSS file: failed at ` ` test3.css on line 2, at column 7 in /css/src/Parser.php:149
```


These are all legal CSS and so should be parsed as CSS. They work fine if I name them `.scss` files
