### ISSUE TITLE
Fix escaped char normalization in keyword

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#167]

**Comment by Cerdic** [comment]
In link to #164 and as seen in https://sass-lang.com/documentation/values/strings#escapes

<img width="1017" alt="Capture d’écran 2020-08-31 à 14 26 10" src="https://user-images.githubusercontent.com/342805/91719621-f3bb1500-eb95-11ea-8347-bb2a29496236.png">

**Comment by Cerdic** [comment]
Note that this seems to be a quite recent change in dart-sass, and none of the other libs are supporting that

**Comment by leonardfischer** [comment]
I noticed a similiar problem with bootstrap, with the previous version the output looked like this:

```css
.blockquote-footer::before{content:"\2014\00A0"}
```

With version 1.2 it looks like this:
```css
.blockquote-footer::before{content:"— "}
```
