### ISSUE TITLE
Parser error due to whitespaces inside not()

### ISSUE THREAD

**Issue by schliesser** [scssphp/scssphp#21]
We are using the mmenu in a project along with the scssphp compiler. As we tried to upgrade the scss compiler from v0.8.2 to 1.0.2 we ran into a parser error:
`parse error: failed at `&:not( .mm-panel_opened ) {` .../mmenu-src/core/oncanvas/_oncanvas.panels.rtl.scss on line 4, at column 3`

As I found out, the errors are caused by whitespaces inside `not()`.  
Parser error:
```scss
.mm-panel {
	&:not( .mm-panel_opened ) {
		transform: translate3d( -100%, 0, 0 );
	}
}
```

Compiles fine:
```scss
.mm-panel {
	&:not(.mm-panel_opened) {
		transform: translate3d( -100%, 0, 0 );
	}
}
```

The parser error occurs first in leafo/scssphp v0.8.3.
Can you add support for whitespaces inside normal brackets?
