### ISSUE TITLE
Implementation of call("if") is not compliant with official Sass implementations

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#216]
```scss
a {
  b: call(get-function("if"), true, "yes", $undefined);
}
```

With this input, all official implementations (dart-sass, libsass and even ruby-sass) are throwing an error about an undefined variable `$undefined` in the arguments of `call`.
Our own implementation makes `call` special in the same way than `if`, delaying the resolution of arguments. And as the `if` function gets called, that makes this snippet return `"yes"` without error.
