### ISSUE TITLE
Breaking change un 1.3 on selector re-parsing (again :/)

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#273]
Related to #245 and compiled selector re-parsing to check they are valid

```scss
/// Utility mixin for grid.
/// @param {list} $gutters Column and row gutters (default is 40px).
/// @param {string} $breakpointName Optional breakpoint name.
@mixin grid($gutters: 40px, $breakpointName: null) {

	// Cells.
		$x: '';
		@if $breakpointName {
			$x: '\\28' + $breakpointName + '\\29';
		}
		.\31 2u#{$x}, .\31 2u\24#{$x} { width: 100%; clear: none; margin-left: 0; }
		.\31 2u\24#{$x} + *,
		.\31 u\24#{$x} + * {
			clear: left;
		}
		.\-11u#{$x} { margin-left: 91.6666666667% }
}
	
.test {
    @include grid(40px, 'xlarge');
}
```

produce
```
`$\28xlarge\29 + *` is not a valid Selector in `.\312u\24\28xlarge\29 + *, .\31u$\28xlarge\29 + *`: failed at `$\28xlarge\29 + *` ScssPhp\ScssPhp\Compiler::evalSelectors on line 1, at column 32
```

Whereas Sassmeister produce

```css
.test .\31 2u\(xlarge\), .test .\31 2u\$\(xlarge\) {
  width: 100%;
  clear: none;
  margin-left: 0;
}
.test .\31 2u\$\(xlarge\) + *,
.test .\31 u\$\(xlarge\) + * {
  clear: left;
}
.test .\-11u\(xlarge\) {
  margin-left: 91.6666666667%;
}
```

The real bug is probably in the selector Parsing here, due to escaped chars in the selectors
