### ISSUE TITLE
Tabs and whitespaces are compiled to css-incompatible values in multi-line selectors

### ISSUE THREAD

**Issue by fabian-mcfly** [scssphp/scssphp#285]
Using thise code
```scss
$var:800;

.Title {
	@media screen AND (max-width:#{$var}px),
	screen AND (max-height:920px) {
		font-size:#{32 / 16}rem;
	}
}
```

you will receive this CSS output, breaking the Media Query:

```scss
@media screen AND (max-width:800px),\d \a \9 screen AND (max-height:920px) {
  .Title {
    font-size: 2rem;
  }
}
``` 

The result must not include `\d \a \9`
