### ISSUE TITLE
Incompatible units error in calc() or variable

### ISSUE THREAD

**Issue by thomashigginbotham** [scssphp/scssphp#352]
An "incompatible units" error is thrown when creating a string variable that includes an interpolated value whose unit is not the same as others in the string (e.g. `$result: 50% - #{$some-rem-unit}`). This also happens inside of `calc()` statements (e.g. `calc(50% - #{$some-rem-unit})`). Both of these cases work fine in Dart Sass.

For now, I'm having to quote then unquote the string as a workaround:

```scss
$some-rem-unit: 2rem;
$result: "50% - #{$some-rem-unit}";
width: calc(#{unquote($result));
```
