### ISSUE TITLE
Comments are parsed (and acts weird)

### ISSUE THREAD

**Issue by Xendiadyon** [scssphp/scssphp#38]
We lately switched to scssphp/scssphp 1.0.3 (from leafo/scssphp) and found two issues, which we were able to trace back to one single problem by tedious debugging.

### Short Bug report
Please DO NOT parse anything inside of /* */ comments!

### Issue 1: Variables in Comments
We had a documentation inside a SCSS file on how to work with a mixin. Here, we had used some comment, which should be absolutely fine.
```CSS
/*
Usage:
@include mediaSwitch(background,red,green,blue);
or using lists:
$imgArea: 550px, 280px, 174px;
@include mediaSwitch(height,$imgArea...);
*/
```

When switching from leafo/scssphp to scssphp/scssphp, this comment was parsed and an error "can not find undeclared variable $imgArea" was thrown.
No, this is absolutely NOT desired!

### Issue 2: Versions in comments
This was great fun to find!
We implemented the tingle library. At the beginning, there was a comment, which should be absolutely fine:
```CSS
/* ----------------------------------------------------------- */
/* == tingle v0.15.1 */
/* ----------------------------------------------------------- */
```
*BUT:* In this comment, there was the version number `v0.15.1` which was parsed by scssphp/scssphp probably to something like: `v0 0.15 0.1`.

At the first sight, this should be no problem, as it is just inside of a comment, right?

However, we noted that *in certain cases*, a self-written Media-Query-Mixin `smallScreen` in a file which was imported **before** the tingle-SCSS-Subfile did not work:
```CSS
@include smallScreen {
  .navBar {
    display: none;
    border: 2px solid yellow; // works
  }
}
@include smallScreen {
  .navBar {
    display: block;
    border: 2px solid orange; // works
  }
}
.navBar
{
  @include smallScreen {
    border:2px solid green; // works
  }
  display:block;
  border:2px solid blue;
  @include smallScreen {
    border:2px solid blueviolet; // works
  }
  @include smallScreen {
    div
    {
      border:2px solid purple; // DOES NOT WORK
    }
  }
}
```

I can't tell why exactly this number-reformating led to such a strange behavior.
Alas, it doesn't matter.
If there is nothing parsed inside the comment section /* */, these two issues should not occur again.

Thank you :)
