### ISSUE TITLE
Variables interpolation bug

### ISSUE THREAD

**Issue by Seonic** [scssphp/scssphp#40]
Source data:
```scss
$theme: 'theme';
$font: sans-serif;
a {
  font: var(--#{$theme}-font, $font);
}
```
Compiled results:
```css
a {
  font: var(-- theme-font, sans-serif);
}
```
Exprected results:
```css
a {
  font: var(--theme-font, sans-serif);
}
```
