### ISSUE TITLE
1.5.2 fails with Only 1 argument allowed, but 2 were passed.

### ISSUE THREAD

**Issue by magicdude4eva** [scssphp/scssphp#420]
Error: Only 1 argument allowed, but 2 were passed on line 6, at column 5
```scss
@mixin form-control-focus($color: $input-border-focus) {
  $color-rgba: rgba(red($color), green($color), blue($color), .6);
  &:focus {
    border-color: $color;
    outline: 0;
    @include box-shadow(inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px $color-rgba);
  }
}
```
