### ISSUE TITLE
Bug found `)a`

### ISSUE THREAD

**Issue by janstieler** [scssphp/scssphp#447]
Hi,
if I use
```scss
:nth-child(3n+2) {
        a {
            padding-top: 0;
            padding-right: 0;
        }
}
```
it will be parsed as
```css
:nth-child(3n+2)a {
            padding-top: 0;
            padding-right: 0;
}
```

Cheers

**Comment by stof** [comment]
@janstieler Which version of scssphp are you using ? With 1.6.0, I get the expected output.

**Comment by janstieler** [comment]
I had the 1.5.2 and updated actually to the 1.6.0 but the space mistake further exist.

Here is the complete nested part of my classes.
```css
.masonry-item {
    width: 14vw;
    margin-bottom: 30px;
    &:first-child {
        .masonry-link {
            padding-top: 0;
            padding-left: 0;
        }
    }
    &:nth-child(3n+2) .masonry-link {
        padding-top: 0;
        padding-right: 0;
    }
    .masonry-link {
        display: flex;
        padding: 1vw;
    }
    img {
        width: 100%;
    }
}
```
I changed the a to the class .masonry-link and added als an & to the :nth-child(3n+2).
In my compiled css it deleted the space between the `&:nth-child(3n+2)` and `.masonry-link`.

**Comment by stof** [comment]
I don't see any issue when taking your code snippet and running it through scssphp either. Here is the output I got:

```css
.masonry-item {
  width: 14vw;
  margin-bottom: 30px;
}
.masonry-item:first-child .masonry-link {
  padding-top: 0;
  padding-left: 0;
}
.masonry-item:nth-child(3n+2) .masonry-link {
  padding-top: 0;
  padding-right: 0;
}
.masonry-item .masonry-link {
  display: flex;
  padding: 1vw;
}
.masonry-item img {
  width: 100%;
}
```
