### ISSUE TITLE
Variables scope issues

### ISSUE THREAD

**Issue by jducro** [scssphp/scssphp#46]
I'm trying to compile bootstrap within a block

```scss
.dp-po {
  @import "vendor/bootstrap";
}
```

But I have 2 scope related issues: 
First keyframes are not keeping their parent scope :
```scss
@if $enable-transitions {
  @keyframes progress-bar-stripes {
    from { background-position: $progress-height 0; }
    to { background-position: 0 0; }
  }
}
```
`$progress-height` is defined within bootstrap but I have to redeclare outside my block

mixin are a marker in here: https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L4070

So the function jump to the `rootEnv` and skip all my bootstrap variables. The problem happen in the rfs mixin even with variable declared in the same file:
https://github.com/twbs/bootstrap/blob/master/scss/vendor/_rfs.scss#L135

I manage to compile everything properly by just adding `false &&` at the beginning of the if.
