### ISSUE TITLE
Nested declarations are not spec compliant

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#469]
This is about things like that:

```scss
a {
  b: {
    c: d;
    e: f;
  }
}
```

which should produce a CSS like that:

```css
a {
  b-c: d;
  b-e: f;
}
```
