### ISSUE TITLE
Notice: Trying to get property 'sourceIndex' of non-object in vendor/scssphp/scssphp/src/Compiler.php on line 4481

### ISSUE THREAD

**Issue by connerbw** [scssphp/scssphp#47]
I'm doing dumb things with `append`, `@import` and an `@each` loop, I'm getting:

> Notice: Trying to get property 'sourceIndex' of non-object in vendor/scssphp/scssphp/src/Compiler.php on line 4481

> Notice: Undefined index: in vendor/scssphp/scssphp/src/Compiler.php on line 4481

Using v1.0.4

Help?

**Comment by connerbw** [comment]
Here's the SCSS that seems to trigger this error, not sure how helpful this is out of context:

Seems to happen when `$shapeshifter-font-1` and `$shapeshifter-font-2` are identical.

```scss
$shapeshifter-fonts: ();

@if variable-exists(shapeshifter-font-1) {
  $shapeshifter-fonts: append($shapeshifter-fonts, $shapeshifter-font-1, ',' )
}

@if variable-exists(shapeshifter-font-2) {
  $shapeshifter-fonts: append($shapeshifter-fonts, $shapeshifter-font-2, ',' )
}

@each $font in $shapeshifter-fonts {
  @if unquote($font) == 'Cormorant Garamond' {
    @import 'CormorantGaramondFont';
  } @else if unquote($font) == 'Noto serif' {
    @import 'NotoSerifFont';
  } @else if unquote($font) == 'Spectral' {
    @import 'SpectralFont';
  } @else if unquote($font) == 'Alegreya' {
    @import 'AlegreyaSansSCFont';
  } @else if unquote($font) == 'Crimson Text' {
    @import 'CrimsonTextFont';
  } @else if unquote($font) == 'Roboto' {
    @import 'RobotoFont';
  } @else if unquote($font) == 'Open Sans' {
    @import 'OpenSansFont';
  } @else if unquote($font) == 'Lato' {
    @import 'LatoFont';
  } @else if unquote($font) == 'Montserrat' {
    @import 'MontserratFont';
  } @else if unquote($font) == 'Raleway' {
    @import 'RalewayFont';
  } @else if unquote($font) == 'Noto Sans' {
    @import 'NotoSansFont';
  } @else if unquote($font) == 'Rubik' {
    @import 'RubikFont';
  } @else if unquote($font) == 'Barlow' {
    @import 'BarlowFont';
  } @else if unquote($font) == 'Libre Franklin' {
    @import 'LibreFranklinFont';
  } @else if unquote($font) == 'K2D' {
    @import 'K2DFont';
  }
}
```
