### ISSUE TITLE
$compiler->compileString() cannot compile the variables inside the :root.

### ISSUE THREAD

**Issue by ahamed** [scssphp/scssphp#496]
If I write SCSS variables inside the `:root {}` then the variable does not compiled to CSS.

#### My code:
```scss
/** scss/index.scss */
:root {
    --theme-color: $theme_color;
}
```

#### Expected result:
```css
/** css/style.css */
:root {
    --theme-color: #F2F2F2;
}
```

#### Actual result:
```css
/** css/style.css */
:root {
    --theme-color: $theme_color;
}
```

Note: Other than the `:root{}` everything working fine.
