### ISSUE TITLE
Misleading error message when passing percentage instead of scalar between 0 and 1

### ISSUE THREAD

**Issue by TimWolla** [scssphp/scssphp#586]
```scss
$test: #FFF;

:root {
	color: fade-out($test, 100%);
}
```

results in the error message:

```
Error: $amount: Expected 100% to be within 0% and 1%: test.scss on line 4, at column 2
```

The (re)use of units in the error message, especially for the expected “within” values, makes it unclear that the `fade-out` function does not expect a percentage at all.

A better wording might be:

```
Error: $amount: Expected scalar between '0' and '1', '100%' given: test.scss on line 4, at column 2
```
