### ISSUE TITLE
Attribute selector with class-like content paired with `@extend` generates invalid CSS

### ISSUE THREAD

**Issue by max-m** [scssphp/scssphp#605]
The following input generates some broken output.
Tested on version `1.10.5`.

Input:
=====
```scss
[data-foo='something.data.like'] {
	&[data-show='true'] {
		color: red;
	}
}

[data-foo='something.other.like'] {
	@extend %my-test-class;
}

%my-test-class {
	&[data-show='true'] {
		position: fixed;
	}
}

/////////////////////////////////////////////////////////////////////////////

[data-foo='this-works'] {
	@extend %my-other-class;
}

%my-other-class {
	&[data-show='true'] {
		position: fixed;
	}
}
```

Output:
======
```css
[data-foo="something.data.like"][data-show="true"] {
  color: red;
}
data-foo="something.other.like"][[data-show="true"] {
  position: fixed;
}
[data-foo="this-works"][data-show="true"] {
  position: fixed;
}
```
As you can see, the opening bracket in line 4 got placed after the corresponding closing one.
