### ISSUE TITLE
RGBA with hex not working

### ISSUE THREAD

**Issue by mrelliot69** [scssphp/scssphp#626]
When i use 
background-color: rgba(#f17171, 0.18) !important;
 on my scss, the compiler is not converting to rgba is keeping the hex color, causing an error then on the layouts since the color is invalid

**Comment by stof** [comment]
I don't manage to reproduce it.

My input:

```scss
a{
    background-color: rgba(#f17171, 0.18) !important;
}
```

My output:
```css
a {
  background-color: rgba(241, 113, 113, 0.18) !important;
}
```
