### ISSUE TITLE
HSL values are converted to RGB

### ISSUE THREAD

**Issue by matteo-greco** [scssphp/scssphp#643]
I have some SCSS code that needs to output colors in HSL. Something like this:

```scss
.test-color {
  background-color: hsl(100, 75%, 40%);
}
```

However, they come out in CSS converted in HEX, like this:

```css
.test-color {
  background-color: #4cb31a;
} 
```

Is there a way to prevent this conversion and keep such colors in HSL?
