### ISSUE TITLE
Uncaught AssertionError: assert($this->env !== null) in Parser.php:1686

### ISSUE THREAD

**Issue by matteo-greco** [scssphp/scssphp#689]
I recently upgraded from 1.9.0 to 1.11.1 and I'm now getting an uncaught AssertionError in Parser.php:1686. The actual code that uses the ScssPhp library is much bigger, but the following is a good approximation that does produce the error.

```php
$compiler = new Compiler();
$variables = array(
    'box-shadow-1-name' => 'm',
    'box-shadow-1-value' => '0 -4px 4px -10px rgba(255, 255, 255, 0.02), /* Schatten nach oben */ 0 4px 4px -10px rgba(255, 255, 255, 0.02), /* Schatten nach unten */ 0 -13px 13px -10px rgba(255, 255, 255, 0.03),/* Stärkerer Schatten nach oben */ 0 13px 13px -10px rgba(255, 255, 255, 0.03), /* Stärkerer Schatten nach unten */ 0 -40px 60px -10px rgba(255, 255, 255, 0.04),/* Stärkster Schatten nach oben */ 0 40px 60px -10px rgba(255, 255, 255, 0.04); /* Stärkster Schatten nach unten */',
);

$scss_contents = '
$box-shadow-1-name: m !default;
$box-shadow-1-value: 0 4px 4px -10px hsla(0, 0, 0, 0.04),
  0 13px 13px -10px hsla(0, 0, 0, 0.06),
  0 40px 60px -10px hsla(0, 0, 0, 0.08) !default;

.box-shadow--#{$box-shadow-1-name} {
box-shadow: $box-shadow-1-value;
}
';

$compiler_variables = array();
foreach ( $variables as $var_id => $var_value ) {
    try {
        $compiler_variables[ $var_id ] = ValueConverter::parseValue($var_value);
    } catch ( InvalidArgumentException $e ) {
        $error_message = sprintf('%s: error while parsing variable %s (value: "%s"): %s', __METHOD__, $var_id, $var_value, $e->getMessage());
        error_log($error_message);
    }
}
$compiler->addVariables($compiler_variables);
echo $compiler->compileString($scss_contents)->getCss();
```

The issue seems to be the CSS comments in box-shadow-1-value. Escaping them gets rid of the error, but then it produces invalid CSS:

```css
@charset "UTF-8";

.box-shadow--m {
    box-shadow: 0 -4px 4px -10px rgba(255, 255, 255, 0.02), \/* Schatten nach oben *\/ 0 4px 4px -10px rgba(255, 255, 255, 0.02), \/* Schatten nach unten *\/ 0 -13px 13px -10px rgba(255, 255, 255, 0.03), \/* Stärkerer Schatten nach oben *\/ 0 13px 13px -10px rgba(255, 255, 255, 0.03), \/* Stärkerer Schatten nach unten *\/ 0 -40px 60px -10px rgba(255, 255, 255, 0.04), \/* Stärkster Schatten nach oben *\/ 0 40px 60px -10px rgba(255, 255, 255, 0.04);
}
```

This same code used to work in 1.9.0. Any ideas?
