### ISSUE TITLE
Problems with @at-root

### ISSUE THREAD

**Issue by shahroq** [scssphp/scssphp#706]
Working with this project, which extensively uses [@at-root](https://sass-lang.com/documentation/at-rules/at-root/), I found some differences between the result of `scssphp` and SCSS compiler. This is one use-case:
```scss
.container {
  @at-root body#{&} {
     #logo { 
      border: 1px solid red;
    }
  }
}
```

The expected result, as shown [here](https://sass-lang.com/playground/#eJwzNNRLzs8rSczMSy1SqObidEgs0S3Kzy9RSMpPqVSuVqsFCXIq5+Sn5ytUKwCZnEn5RSmpRVYKhgUVCsX5OZkpCkWpKdZAmVouToVarloAFsUYFA==)
```css
body.container #logo {
    border: 1px solid red;
}
```

The scssphp result:
```css
bodybody.container #logo {
  border: 1px solid red;
}
```

**Comment by stof** [comment]
I'm adding that to the 2.0 milestone because our messy implementation of `@at-root`, selector manipulation and nesting in 1.x would require a lot of work to fix it (if even possible).

**Comment by zoglo** [comment]
Same issue as in sass and more of a limitation: https://github.com/sass/sass/issues/2135

You could try
```scss
.container {
  @at-root #{selector-append('body', &)} {
     #logo { 
      border: 1px solid red;
    }
  }
}
```
