### ISSUE TITLE
Issue with pseudoelement selectors order in @extend'ed elements (regression in 1.0.6)

### ISSUE THREAD

**Issue by CrazyManLabs** [scssphp/scssphp#72]
## Description
After updating version of scssphp from `1.0.5` to `1.0.6` I've got a problem with pseudoelement selectors order - they are all messed up, when I `@extend`ing base class (and only in this case, not in base class, that have been extended).

## Steps to reproduce
1. Write some code.
    <details>
    <summary>Reference markup</summary>

    ```html
    <button class="button button--normal">Hello</button>
    <div class="wrapper">
      <div class="test">World</div>
    </div>
    ```
    </details>
    <details>
    <summary>Reference styles</summary>

    ```scss
    .button {
      position: relative;
  
      display: block;
      width: 100%;
  
      cursor: pointer;
      color: inherit;
      border: none;
      background: none;

      &:after {
        content: '';

        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;

        display: block;
        width: 0;

        margin: auto;

        transition: width 0.25s ease-in-out;
      }
  
      &:hover,
      &:focus,
      &:active {
        &:after {
          width: 100%;
        }
      }
  
      &--normal {
        color: white;
        background: darkgreen;
    
        &:after {
          background: rgba(white, 0.25);
        }
      }
    }

    .wrapper {
      & > .test {
        @extend .button;
        @extend .button--normal;
      }
    }
    ```
    </details>
2. Compile styles with reference compiler (I've used codepen.io with its' SCSS preprocessor option (which uses libsass, as I can tell)) and scssphp (both `1.0.5` and `1.0.6`).
    <details>
    <summary>Expected (<code>codepen.io / libsass?</code>)</summary>

    ```css
    .button, .wrapper > .test {
      position: relative;
      display: block;
      width: 100%;
      cursor: pointer;
      color: inherit;
      border: none;
      background: none;
    }
    .button:after, .wrapper > .test:after {
      content: '';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      display: block;
      width: 0;
      margin: auto;
      transition: width 0.25s ease-in-out;
    }
    .button:hover:after, .wrapper > .test:hover:after, .button:focus:after, .wrapper > .test:focus:after, .button:active:after, .wrapper > .test:active:after {
      width: 100%;
    }
    .button--normal, .wrapper > .test {
      color: white;
      background: darkgreen;
    }
    .button--normal:after, .wrapper > .test:after {
      background: rgba(255, 255, 255, 0.25);
    }
    ```
    </details>
    <details>
    <summary>Compiled (<code>scssphp 1.0.5</code>)</summary>

    ```css
    .button, .wrapper > .test {
      position: relative;
      display: block;
      width: 100%;
      cursor: pointer;
      color: inherit;
      border: none;
      background: none;
    }
    .button:after, .wrapper > .test:after {
      content: '';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      display: block;
      width: 0;
      margin: auto;
      transition: width 0.25s ease-in-out;
    }
    .button:hover:after, .wrapper > .test:hover:after, .button:focus:after, .wrapper > .test:focus:after, .button:active:after, .wrapper > .test:active:after {
      width: 100%;
    }
    .button--normal, .wrapper > .test {
      color: white;
      background: darkgreen;
    }
    .button--normal:after, .wrapper > .test:after {
      background: rgba(255, 255, 255, 0.25);
    }
    ```
    </details>
    <details>
    <summary>Compiled (<code>scssphp 1.0.6</code>)</summary>

    ```css
    .button, .wrapper > .test {
      position: relative;
      display: block;
      width: 100%;
      font-family: inherit;
      font-size: inherit;
      line-height: inherit;
      font-style: inherit;
      font-weight: inherit;
      cursor: pointer;
      color: inherit;
      border: none;
      background: none;
    }
    .button:after, .wrapper > .test:after {
      content: '';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      display: block;
      width: 0;
      margin: auto;
      transition: width 0.25s ease-in-out;
    }
    .button:hover:after, .wrapper > .test:after:hover, .button:focus:after, .wrapper > .test:after:focus, .button:active:after, .wrapper > .test:after:active {
      width: 100%;
    }
    .button--normal, .wrapper > .test {
      color: white;
      background: darkgreen;
    }
    .button--normal:after, .wrapper > .test:after {
      background: rgba(255, 255, 255, 0.25);
    }
    ```
    </details>
3. Compare results.
    Version `1.0.5`:
    - [x] doing its' job well (output pretty much the same as reference);
    - [x] buttons in page are getting their (not so fancy) styling on hover, etc.;

    Version `1.0.6`:
    - [x] doing its' job well for base class (`.button`);
    - [ ] for selector, that extending base class (`.wrapper > .test`), all pseudoelement selectors got messed up (`:after:hover` instead of `:hover:after`, etc.);
    - [x] button with base class got its' styling;
    - [ ] button with extended selector (of course) is not getting styling on hover.

Am I doing something wrong (in this case why codepen's compiler and version `1.0.5` are getting the same output?) or is something wrong with `1.0.6` update ([commit #2bea5ef](https://github.com/scssphp/scssphp/commit/2bea5ef6b06e2ae527f102808d135d654d1b4391) may be?)
