### ISSUE TITLE
Backslashes in quotes get sometimes removed

### ISSUE THREAD

**Issue by MatzeKitt** [scssphp/scssphp#784]
I’m using a very basic implementation as described in the documentation with version 2.0.0, installed via Composer:

```php
require_once __DIR__ . '/../vendor/autoload.php';
		
$compiler = new Compiler();
echo $compiler->compileString( $code )->getCss();
```

Where `$code` is this string:

```scss
.test {
	content: "\u00a9";
	
	.nested {
		display: block;
	}
}
```

**Expected output:**

```css
.test {
  content: "\u00a9";
}
.test .nested {
  display: block;
}
```

**Actual output:**

```css
.test {
  content: "u00a9";
}
.test .nested {
  display: block;
}
```

As you can see, the backslash inside the quotes for `content` is getting removed in line 2.

Interestingly, this doesn’t always happen. If I use `content: "\f015"` for example, the backslash persists in the compiled CSS.
